[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["Ethan <ethan@no-reply.com>"]

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"
diesel = { version = "<= 1.2", features = ["sqlite", "r2d2"] }
